[tool.poetry]
name = "reflex-test"
version = "0.1.0"
description = ""
authors = ["Tim Child <timjchild@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
reflex = "^0.4.8"
google-auth = {extras = ["requests"], version = "^2.29.0"}
python-dotenv = "^1.0.1"
reflex-webcam = "^0.0.5"
pillow = "^10.3.0"
reflex-carousel = "^0.0.1"
stripe = "^9.1.0"
reflex-audio-capture = "^0.0.2"
fakeredis = "^2.23.0"
dill = "^0.3.8"


[tool.poetry.group.dev.dependencies]
ruff = "^0.3.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120

[tool.ruff.format]
docstring-code-format = true

